### ISSUE TITLE
Glances install gives an error

### ISSUE THREAD

**Issue by gignonje** [notFloran/environment#3]
Installing glances gives an error that seems related to access rights:

The error is:
error: could not create '/usr/local/lib/python2.7/dist-packages/glances': Permission denied

Thank you

**Comment by notFloran** [comment]
Comment for me:

"une commande si le module détecte que glances est déjà installé > pip install --upgrade Glances
une commande si le module détecte que glances n'est pas installé > curl -L http://bit.ly/glances | /bin/bash"
